"""Aggregate the v0.4 rescue run vs the v0.4 baselines.

Compares B6_NoCIS (with rescue path) — 3-seed mean ± std — to:
  - S7_SelfRefine (best baseline in v0.4)
  - S1_Direct, B4_ViviDoc, B1-B3 (full baseline grid)
  - Original B6_Full 3-seed (for delta)

Outputs a markdown summary mirroring outputs/v0.4/reports/v04_SOTA_final.md.
"""
from __future__ import annotations

import argparse
import json
import math
import statistics
from collections import defaultdict
from pathlib import Path


AXES = (
    "faithfulness",
    "coverage",
    "type_appropriateness",
    "cross_document_integration",
    "search_query_quality",
)
SOURCES = ("10k", "arxiv", "govreport", "hotpotqa", "multinews", "tech_docs")


def load(p: Path) -> list:
    return json.loads(Path(p).read_text(encoding="utf-8"))


def mean(xs):
    xs = [x for x in xs if x is not None]
    return sum(xs) / len(xs) if xs else 0.0


def std(xs):
    xs = [x for x in xs if x is not None]
    if len(xs) < 2:
        return 0.0
    m = sum(xs) / len(xs)
    return math.sqrt(sum((x - m) ** 2 for x in xs) / (len(xs) - 1))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rescue-judge-dir", required=True,
                    help="Dir with b6_nocis_seed{42,43,44}.json")
    ap.add_argument("--baselines-judge", required=True,
                    help="Path to v0.4 baselines.json (1800 records)")
    ap.add_argument("--b6-full-judge-dir", default="outputs/v0.4/judge",
                    help="Dir with original b6_seed{42,43,44}.json (B6_Full)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    rescue_dir = Path(args.rescue_judge_dir)
    seeds = [42, 43, 44]
    b6_nc_records = {}  # seed -> list[record]
    for s in seeds:
        p = rescue_dir / f"b6_nocis_seed{s}.json"
        if not p.exists():
            print(f"[warn] missing {p}")
            continue
        b6_nc_records[s] = load(p)

    full_dir = Path(args.b6_full_judge_dir)
    b6_full_records = {}
    for s in seeds:
        p = full_dir / f"b6_seed{s}.json"
        if p.exists():
            b6_full_records[s] = load(p)

    baselines = load(args.baselines_judge)
    bl_by_qid_strat = defaultdict(dict)
    for r in baselines:
        bl_by_qid_strat[r["query_id"]][r["strategy"]] = r

    lines = []
    lines.append("# v0.4 RESCUE — B6_NoCIS + sidecar rescue\n")
    lines.append("Generated by `code/scripts/aggregate_rescue.py`.\n")

    # ── §1 3-seed overall ────────────────────────────────────────────────
    lines.append("## §1. B6_NoCIS_rescue — 3-seed overall\n")
    seed_means_nc = {}
    for s, recs in b6_nc_records.items():
        m = mean([r["overall"] for r in recs])
        seed_means_nc[s] = m
        lines.append(f"- seed{s}: overall = **{m:.4f}** (n={len(recs)})")
    if seed_means_nc:
        vals = list(seed_means_nc.values())
        lines.append(
            f"\n- **3-seed mean ± std = "
            f"{mean(vals):.4f} ± {std(vals):.4f}** (n_seeds={len(vals)})\n"
        )

    # B6_Full reference
    seed_means_full = {
        s: mean([r["overall"] for r in recs])
        for s, recs in b6_full_records.items()
    }
    if seed_means_full:
        vals = list(seed_means_full.values())
        lines.append("## §2. B6_Full (V4_cons) reference — original v0.4\n")
        for s, m in seed_means_full.items():
            lines.append(f"- seed{s}: {m:.4f}")
        lines.append(
            f"\n- 3-seed mean ± std = {mean(vals):.4f} ± {std(vals):.4f}\n"
        )

    # Δ rescue − full
    if seed_means_nc and seed_means_full:
        delta = mean(list(seed_means_nc.values())) - mean(list(seed_means_full.values()))
        lines.append(f"### Δ (NoCIS_rescue − B6_Full) = **{delta:+.4f}**\n")

    # ── §3 per-axis (seed42) ─────────────────────────────────────────────
    if 42 in b6_nc_records:
        recs = b6_nc_records[42]
        lines.append("## §3. NoCIS_rescue per-axis (seed42)\n")
        for ax in AXES:
            vals = [r["axis_scores"].get(ax) for r in recs]
            lines.append(f"- {ax}: {mean(vals):.4f}")
        lines.append("")

    # ── §4 per-source (seed42) ───────────────────────────────────────────
    if 42 in b6_nc_records:
        lines.append("## §4. Per-source (seed42)\n")
        lines.append("| source | NoCIS_rescue | S1_Direct | S7_SelfRefine | Δ(S7−us) |")
        lines.append("|---|---|---|---|---|")
        nc_by_src = defaultdict(list)
        for r in b6_nc_records[42]:
            nc_by_src[r["source"]].append(r["overall"])
        s1_by_src = defaultdict(list)
        s7_by_src = defaultdict(list)
        for qid, strats in bl_by_qid_strat.items():
            if "S1_Direct" in strats:
                r = strats["S1_Direct"]
                s1_by_src[r["source"]].append(r["overall"])
            if "S7_SelfRefine" in strats:
                r = strats["S7_SelfRefine"]
                s7_by_src[r["source"]].append(r["overall"])
        for src in SOURCES:
            nc = mean(nc_by_src[src])
            s1 = mean(s1_by_src[src])
            s7 = mean(s7_by_src[src])
            lines.append(
                f"| {src} (n={len(nc_by_src[src])}) | {nc:.3f} | {s1:.3f} | {s7:.3f} | {s7-nc:+.3f} |"
            )
        lines.append("")

    # ── §5 vs baselines ──────────────────────────────────────────────────
    lines.append("## §5. Baselines vs NoCIS_rescue\n")
    lines.append("| strategy | n | overall | Δ vs NoCIS_3seed |")
    lines.append("|---|---|---|---|")
    by_strat = defaultdict(list)
    for r in baselines:
        by_strat[r["strategy"]].append(r["overall"])
    nc_3 = mean(list(seed_means_nc.values())) if seed_means_nc else 0
    rows = []
    for strat, vals in by_strat.items():
        m = mean(vals)
        rows.append((strat, len(vals), m, m - nc_3))
    rows.sort(key=lambda x: -x[2])
    for strat, n, m, d in rows:
        lines.append(f"| {strat} | {n} | {m:.4f} | {d:+.4f} |")
    if seed_means_nc:
        sd = std(list(seed_means_nc.values()))
        lines.append(
            f"| **B6_NoCIS_rescue (3-seed)** | 300×{len(seed_means_nc)} | "
            f"**{nc_3:.4f} ± {sd:.4f}** | reference |"
        )
    if seed_means_full:
        m_full = mean(list(seed_means_full.values()))
        sd_full = std(list(seed_means_full.values()))
        lines.append(
            f"| B6_Full (3-seed, original v0.4) | 300×{len(seed_means_full)} | "
            f"{m_full:.4f} ± {sd_full:.4f} | {m_full - nc_3:+.4f} |"
        )
    lines.append("")

    # ── §6 syntax + infra failure rates ──────────────────────────────────
    if 42 in b6_nc_records:
        recs = b6_nc_records[42]
        zero_rec = [r for r in recs if r["overall"] == 0]
        invalid = [r for r in recs if not r.get("syntax_valid")]
        lines.append("## §6. Infrastructure quality (seed42)\n")
        lines.append(f"- zero-score records: **{len(zero_rec)}** / {len(recs)}")
        lines.append(f"- syntax_invalid: **{len(invalid)}** / {len(recs)}")
        lines.append("")

    # ── §7 bottom line ───────────────────────────────────────────────────
    lines.append("## §7. Bottom line\n")
    if seed_means_nc:
        nc_3 = mean(list(seed_means_nc.values()))
        sd = std(list(seed_means_nc.values()))
        s7_overall = mean(by_strat.get("S7_SelfRefine", []))
        lines.append(
            f"- B6_NoCIS_rescue 3-seed = **{nc_3:.4f} ± {sd:.4f}**"
        )
        lines.append(f"- S7_SelfRefine = {s7_overall:.4f}")
        lines.append(f"- Δ = **{nc_3 - s7_overall:+.4f}**")
        verdict = "SOTA" if nc_3 >= s7_overall else (
            "statistical tie (within 1σ)" if abs(nc_3 - s7_overall) <= sd else "below SOTA"
        )
        lines.append(f"- Verdict: **{verdict}**")
    lines.append("")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[aggregate_rescue] wrote {out_path}")


if __name__ == "__main__":
    raise SystemExit(main() or 0)
